---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service:3306

            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                   name: mysql-credentials 
                   key:  username

            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: mysql-credentials
                   key:  password
          ports:
            - containerPort: 80
              name: wordpress
...
